# Generated by Django 3.2.6 on 2021-10-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_collection', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('description', models.TextField(blank=True)),
                ('draft', models.BooleanField(default=False, help_text='публиковать/ скрыть')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.CharField(max_length=7, unique=True)),
                ('format_file', models.CharField(max_length=3, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dressed.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name_collection',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Imagecollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='imagecollection/')),
                ('draft', models.BooleanField(default=False, help_text='публиковать/ скрыть')),
                ('collectionpresent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecollection', to='dressed.product')),
            ],
            options={
                'verbose_name': 'imagecollection',
                'verbose_name_plural': 'imagecollections',
                'ordering': ['-title'],
            },
        ),
    ]
