# Generated by Django 3.2.6 on 2021-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='format_file',
            field=models.TextField(blank=True),
        ),
    ]
