# Generated by Django 3.2.6 on 2021-10-14 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dressed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('about', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='course')),
                ('lessons_circle', models.DecimalField(decimal_places=1, max_digits=10)),
                ('circle', models.DecimalField(decimal_places=1, max_digits=10)),
                ('time', models.TextField(max_length=51)),
                ('online', models.TextField(blank=True, max_length=10)),
                ('alive', models.TextField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='format_file',
            field=models.TextField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TextField(max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='users/')),
                ('full_height', models.DecimalField(blank=True, decimal_places=2, help_text='полный рост', max_digits=10, null=True)),
                ('neck_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват шеи', max_digits=10, null=True)),
                ('chest_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват груди', max_digits=10, null=True)),
                ('chest_height', models.DecimalField(blank=True, decimal_places=2, help_text='высота груди', max_digits=10, null=True)),
                ('center_chest', models.DecimalField(blank=True, decimal_places=2, help_text='центр груди', max_digits=10, null=True)),
                ('back_width', models.DecimalField(blank=True, decimal_places=2, help_text='ширина спинки', max_digits=10, null=True)),
                ('shoulder_long', models.DecimalField(blank=True, decimal_places=2, help_text='длина плеча', max_digits=10, null=True)),
                ('long_sleeves', models.DecimalField(blank=True, decimal_places=2, help_text='длинна рукава', max_digits=10, null=True)),
                ('arm_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват руки (плеча)', max_digits=10, null=True)),
                ('wrist_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват кисти', max_digits=10, null=True)),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=2, help_text='обхват талии', max_digits=10, null=True)),
                ('length_front_waist', models.DecimalField(blank=True, decimal_places=2, help_text='длинна переда до талии', max_digits=10, null=True)),
                ('long_back_waist', models.DecimalField(blank=True, decimal_places=2, help_text='длинна спины к талии', max_digits=10, null=True)),
                ('long_waist_knee', models.DecimalField(blank=True, decimal_places=2, help_text='длинна от талии до колена', max_digits=10, null=True)),
                ('hip_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват бедер', max_digits=10, null=True)),
                ('thigh_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват бедра', max_digits=10, null=True)),
                ('knee_girth', models.DecimalField(blank=True, decimal_places=2, help_text='обхват колена', max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
