# Generated by Django 3.2.6 on 2021-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0002_alter_product_format_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='format_file',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
