# Generated by Django 3.2.6 on 2021-10-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0002_auto_20211014_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(max_length=500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='alive',
            field=models.TextField(blank=True, max_length=10, verbose_name='Зустрічи'),
        ),
        migrations.AlterField(
            model_name='course',
            name='circle',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Кількість курсів'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='course', verbose_name='Презентаційне зображення'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_circle',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Занять у 1 курсі'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наіменування курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='online',
            field=models.TextField(blank=True, max_length=10, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TextField(max_length=51, verbose_name='Годин на 1 день'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagecollection/', verbose_name='Зображення ветрикального формату 16:9 або квадрат'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за модель'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Ім*я створювача,сьогоднішня дата '),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dressed.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='format_file',
            field=models.TextField(blank=True, max_length=5, verbose_name='Формат електронного документу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='Презентаційне зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_collection',
            field=models.CharField(max_length=200, unique=True, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за колекцію'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TextField(blank=True, max_length=3, verbose_name='Години консультацій за 1 модель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='arm_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват руки (плеча)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='back_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина спинки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='center_chest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Центр грудей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chest_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват грудей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chest_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Висота грудей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=100, verbose_name='Ваше місто'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Повний зріст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hip_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват стегон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='knee_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват коліна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='length_front_waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Довжина переду до талії'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long_back_waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Довжина спини до талії'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long_sleeves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Довжина рукава'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long_waist_knee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Довжина від талії до коліна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neck_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват шиї'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='Контактний номер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_long',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Довжина плеча'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thigh_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват стегна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват талії'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wrist_girth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обхват кисті'),
        ),
    ]
