# Generated by Django 3.2.6 on 2021-10-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0003_alter_product_format_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TextField(max_length=7, unique=True),
        ),
    ]
