# Generated by Django 3.2.6 on 2021-10-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0003_auto_20211014_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='arm_girth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='back_width',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='center_chest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chest_girth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chest_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hip_girth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='knee_girth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='length_front_waist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='long_back_waist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='long_sleeves',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='long_waist_knee',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neck_girth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shoulder_long',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thigh_girth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='waist_circumference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wrist_girth',
        ),
    ]
