# Generated by Django 3.2.6 on 2021-10-06 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dressed', '0004_alter_product_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('full_height', models.DecimalField(decimal_places=2, help_text='полный рост', max_digits=10)),
                ('neck_girth', models.DecimalField(decimal_places=2, help_text='обхват шеи', max_digits=10)),
                ('chest_girth', models.DecimalField(decimal_places=2, help_text='обхват груди', max_digits=10)),
                ('chest_height', models.DecimalField(decimal_places=2, help_text='высота груди', max_digits=10)),
                ('center_chest', models.DecimalField(decimal_places=2, help_text='центр груди', max_digits=10)),
                ('back_width', models.DecimalField(decimal_places=2, help_text='ширина спинки', max_digits=10)),
                ('shoulder_long', models.DecimalField(decimal_places=2, help_text='длина плеча', max_digits=10)),
                ('long_sleeves', models.DecimalField(decimal_places=2, help_text='длинна рукава', max_digits=10)),
                ('arm_girth', models.DecimalField(decimal_places=2, help_text='обхват руки (плеча)', max_digits=10)),
                ('wrist_girth', models.DecimalField(decimal_places=2, help_text='обхват кисти', max_digits=10)),
                ('waist_circumference', models.DecimalField(decimal_places=2, help_text='обхват талии', max_digits=10)),
                ('length_front_waist', models.DecimalField(decimal_places=2, help_text='длинна переда до талии', max_digits=10)),
                ('long_back_waist', models.DecimalField(decimal_places=2, help_text='длинна спины к талии', max_digits=10)),
                ('long_waist_knee', models.DecimalField(decimal_places=2, help_text='длинна от талии до колена', max_digits=10)),
                ('hip_girth', models.DecimalField(decimal_places=2, help_text='обхват бедер', max_digits=10)),
                ('thigh_girth', models.DecimalField(decimal_places=2, help_text='обхват бедра', max_digits=10)),
                ('knee_girth', models.DecimalField(decimal_places=2, help_text='обхват колена', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
