# Generated by Django 3.2.6 on 2021-10-17 12:36

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0008_auto_20211017_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
