# Generated by Django 3.2.6 on 2021-10-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0008_auto_20211006_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
