# Generated by Django 3.2.6 on 2021-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0010_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alive',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='online',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='circle',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_circle',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
