# Generated by Django 3.2.6 on 2021-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0011_auto_20211008_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
