# Generated by Django 3.2.6 on 2021-10-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
