# Generated by Django 3.2.6 on 2021-10-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0015_remove_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='collection',
        ),
    ]
