# Generated by Django 3.2.6 on 2021-10-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0020_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dressed.category', verbose_name='Категорія'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='draft',
            field=models.BooleanField(default=False, help_text='публиковать/ скрыть', verbose_name='Сховати'),
        ),
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, help_text='публиковать/ скрыть', verbose_name='Сховати'),
        ),
    ]
