# Generated by Django 3.2.6 on 2021-11-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0021_auto_20211020_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='alive',
            field=models.TextField(blank=True, max_length=10, verbose_name='Meetings'),
        ),
        migrations.AlterField(
            model_name='course',
            name='circle',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Number of courses'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='course', verbose_name='Presentation image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_circle',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Classes in 1 course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='online',
            field=models.TextField(blank=True, max_length=10, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TextField(max_length=51, verbose_name='Hours for 1 day'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='draft',
            field=models.BooleanField(default=False, help_text='публиковать/ скрыть', verbose_name='Hide'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='format_file',
            field=models.TextField(blank=True, max_length=5, verbose_name='Electronic document format'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagecollection/', verbose_name='vertical 16: 9 or square image'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per model'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='time',
            field=models.TextField(blank=True, max_length=3, verbose_name='Hours of consultations for 1 model'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Name of the creator and today date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressed.category', verbose_name='Clothing category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='order/', verbose_name='Download image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='massege',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Addition'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dressed.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, help_text='публиковать/ скрыть', verbose_name='Hide'),
        ),
        migrations.AlterField(
            model_name='product',
            name='format_file',
            field=models.TextField(blank=True, max_length=5, verbose_name='Electronic document format'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='Presentation image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_collection',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TextField(blank=True, max_length=3, verbose_name='Hours of consultations for 1 model'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='arm_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Forearm girth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='back_width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Back width'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='center_chest',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='The center of the chest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chest_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Chest girth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chest_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Chest height'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=100, verbose_name='Your city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Full height'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair',
            field=models.TextField(blank=True, max_length=100, verbose_name='Color of hair'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hip_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Thigh circumference'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='knee_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Knee girth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='length_front_waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Length in front to the waist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long_back_waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='The length of the back to the waist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long_sleeves',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Sleeve length'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long_waist_knee',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Length from waist to knee'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neck_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Neck girth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_long',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Shoulder length'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thigh_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Scope tightened'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Waist circumference'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wrist_girth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Brush girth'),
        ),
    ]
