# Generated by Django 3.2.6 on 2021-11-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0024_remove_order_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hair',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, max_length=27, verbose_name='Phone'),
        ),
    ]
