# Generated by Django 3.2.6 on 2021-11-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0025_auto_20211107_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons_circle',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AlterField(
            model_name='course',
            name='alive',
            field=models.TextField(blank=True, max_length=10, verbose_name='Alive'),
        ),
        migrations.AlterField(
            model_name='order',
            name='massege',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Your wishes'),
        ),
        migrations.CreateModel(
            name='Imagecourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='studentimage', verbose_name='Studentimage')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='dressed.course', verbose_name='Course')),
            ],
        ),
    ]
