# Generated by Django 3.2.6 on 2021-11-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0026_auto_20211120_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecourse',
            options={'ordering': ['-image']},
        ),
    ]
