# Generated by Django 3.2.6 on 2021-11-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0037_rename_cat_formteach_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='formteach',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='agreement'),
        ),
        migrations.AlterField(
            model_name='formteach',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressed.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='formteach',
            name='massege',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='What do you expect from the course'),
        ),
    ]
