# Generated by Django 3.2.6 on 2021-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0038_auto_20211128_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='I accept the Terms of Service and Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='formteach',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='I accept the Terms of Service and Privacy Policy'),
        ),
    ]
