# Generated by Django 3.2.6 on 2021-11-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0039_auto_20211128_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formteach',
            new_name='OrderTeach',
        ),
    ]
