# Generated by Django 3.2.6 on 2021-12-04 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dressed', '0040_rename_formteach_orderteach'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='id_orderform', verbose_name='Number order')),
                ('material', models.TextField(max_length=600, verbose_name='Materials for model')),
                ('document', models.FileField(upload_to='documents_collection_user/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dressed.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['-video'],
            },
        ),
    ]
