# Generated by Django 3.2.6 on 2021-12-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0041_collectionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionuser',
            name='ordernumber',
            field=models.PositiveIntegerField(default=0, help_text='id_orderform', verbose_name='Number order'),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dressed.order'),
        ),
    ]
