# Generated by Django 3.2.6 on 2021-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0044_collectionuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='document',
            field=models.FileField(upload_to='user/documents_collection/'),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/imgusercollection/'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='clothesmodel',
            field=models.FileField(blank=True, null=True, upload_to='clothes/clothesmodel/', verbose_name='clothesmodel'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, upload_to='clothes/imagecollection/', verbose_name='vertical 16: 9 or square image'),
        ),
        migrations.AlterField(
            model_name='imagecourse',
            name='image',
            field=models.ImageField(blank=True, upload_to='learn/studentimage', verbose_name='Studentimage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='clothes/order/', verbose_name='Download image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='clothes/product/', verbose_name='Presentation image'),
        ),
    ]
