# Generated by Django 3.2.6 on 2021-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0045_auto_20211205_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='document',
            field=models.FileField(upload_to='data/user/documents_collection/'),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='data/user/img_user_collection/'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='clothesmodel',
            field=models.FileField(blank=True, null=True, upload_to='data/clothes/clothesmodel/', verbose_name='clothesmodel'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, upload_to='data/clothes/imagecollection/', verbose_name='vertical 16: 9 or square image'),
        ),
        migrations.AlterField(
            model_name='imagecourse',
            name='image',
            field=models.ImageField(blank=True, upload_to='data/learn/studentimage', verbose_name='Studentimage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='data/clothes/order/', verbose_name='Download image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='data/clothes/product/', verbose_name='Presentation image'),
        ),
    ]
