# Generated by Django 3.2.6 on 2021-12-05 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0046_auto_20211205_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='clothingparameters',
            field=models.TextField(help_text='parameters: pg96,gk107', null=True, verbose_name='Clothing parameters'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='data/learn/course', verbose_name='Presentation image'),
        ),
    ]
