# Generated by Django 3.2.6 on 2021-12-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0047_auto_20211205_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionuser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='dressed.category', verbose_name='Category'),
        ),
    ]
