# Generated by Django 3.2.6 on 2021-12-12 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dressed', '0048_collectionuser_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
