# Generated by Django 3.2.6 on 2021-12-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0049_alter_collectionuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecollection',
            name='clothesmodel',
        ),
    ]
