# Generated by Django 3.2.6 on 2021-12-13 18:11

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0051_auto_20211212_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollection',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Name of the creator'),
        ),
    ]
