# Generated by Django 3.2.6 on 2021-12-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0053_auto_20211219_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecollection',
            options={'ordering': ['-created'], 'verbose_name': 'imagecollection', 'verbose_name_plural': 'imagecollections'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='format_file',
        ),
    ]
