# Generated by Django 3.2.6 on 2021-12-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0054_auto_20211219_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionuser',
            options={'ordering': ['-video'], 'verbose_name': 'collectionuser', 'verbose_name_plural': 'collectionsUser'},
        ),
        migrations.AlterModelOptions(
            name='imagecourse',
            options={'ordering': ['-created']},
        ),
    ]
