# Generated by Django 3.2.6 on 2021-12-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0055_auto_20211228_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionuser',
            options={'ordering': ['-video'], 'verbose_name': 'usercollection', 'verbose_name_plural': 'usercollections'},
        ),
    ]
