# Generated by Django 3.2.6 on 2021-12-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0056_alter_collectionuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionuser',
            options={'ordering': ['-video'], 'verbose_name': 'user_collection', 'verbose_name_plural': 'user_collections'},
        ),
    ]
