# Generated by Django 3.2.6 on 2021-12-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressed', '0057_alter_collectionuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollection',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data/user/file_imagecollection/'),
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='url',
            field=models.SlugField(max_length=90, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Name of the creator'),
        ),
    ]
